name: Build OpenWrt and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. 编译 OpenWrt 镜像
      - name: Build OpenWrt image
        run: |
          echo "PPPOE_USERNAME=adm" >> modules/network/.env
          echo "PPPOE_PASSWORD=123" >> modules/network/.env
          echo "LAN_IP=192.16.2.1" >> modules/network/.env
          echo "CLASH_CONFIG_URL=https://gist.github.com/EkkoG/20a52db0169c4a4769689521b1c5500e/raw/cf61a9397d0bdbd5b6bbad8fbb388ec851116470/clash_example.yaml" >> modules/openclash/.env
          echo "CONFIG_TARGET_KERNEL_PARTSIZE=16" > .env
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=256" >> .env
          echo "MODULES=openclash openclash-as-default" >> .env
          ./run.sh --image=openwrt/imagebuilder:x86-64-23.05.5

      # 3. 将生成的镜像保存为 GitHub Actions 的构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-image
          path: ./output/ # 假设输出镜像在该目录

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1. 下载之前上传的构建产物
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: openwrt-image
          path: ./release/ # 下载到 release 目录

      # 2. 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v1.0.0'  # 发布版本号
          release_name: 'OpenWrt v1.0.0 Release'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的 token

      # 3. 上传编译好的镜像到 Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/openwrt-image.img # 指定镜像文件
          asset_name: openwrt-image-v1.0.0.img
          asset_content_type: application/octet-stream

