name: Build OpenWrt and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check space usage
        if: (!cancelled())
        run: df -hT  

      # 2. 编译 OpenWrt 镜像
      - name: Build OpenWrt image
        run: |
          echo "PPPOE_USERNAME=adm" >> modules/network/.env
          echo "PPPOE_PASSWORD=123" >> modules/network/.env
          echo "LAN_IP=172.16.2.1" >> modules/network/.env
          echo "CLASH_CONFIG_URL=https://gist.github.com/EkkoG/20a52db0169c4a4769689521b1c5500e/raw/cf61a9397d0bdbd5b6bbad8fbb388ec851116470/clash_example.yaml" >> modules/openclash/.env
          echo "CONFIG_TARGET_KERNEL_PARTSIZE=16" > .env
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=256" >> .env
          echo "MODULES=openclash openclash-as-default" >> .env
          ./run.sh --image=openwrt/imagebuilder:x86-64-23.05.5
  
          
      - name: Upload Build firmware to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file_glob: true
          file: /home/runner/work/OpenWrt/OpenWrt/bin/targets/x86/64/*
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: openwrt-${{ env.VERSION }}-x86_64-${{ env.COMPILE_DATE }}


